// src/screens/patientProfile/addressData.js

export const genderOptions = ["Nam", "Nữ"];
export const ethnicityOptions = [
  "Kinh",
  "Tày",
  "Thái",
  "Mường",
  "Khmer",
  "Hoa",
  "Nùng",
  "Dao",
];
export const occupationOptions = [
  "Bác sĩ",
  "Điều dưỡng",
  "Y sĩ",
  "Dược sĩ",
  "Nha sĩ",
  "Nha công",
  "Dược sĩ trung cấp",
  "Cử nhân Điều dưỡng",
  "Hộ lý",
  "Kỹ sư điện",
  "Khác",
];
export const provinceOptions = [
  "Thành phố Hồ Chí Minh",
  "Thành phố Hà Nội",
  "Thành phố Cần Thơ",
  "Thành phố Hải Phòng",
  "Thành phố Đà Nẵng",
  "Tỉnh An Giang",
  "Tỉnh Bà Rịa - Vũng Tàu",
  "Tỉnh Bình Dương",
  "Tỉnh Bình Phước",
  "Tỉnh Bình Thuận",
];
export const districtOptions = {
  "Thành phố Hồ Chí Minh": [
    "Quận 1",
    "Quận 3",
    "Quận 4",
    "Quận 5",
    "Quận 6",
    "Quận 7",
    "Quận 8",
    "Quận 10",
    "Quận 11",
    "Quận 12",
    "Quận Bình Thạnh",
    "Quận Gò Vấp",
    "Quận Phú Nhuận",
    "Quận Tân Bình",
    "Quận Tân Phú",
    "Thành phố Thủ Đức",
  ],
  "Thành phố Hà Nội": [
    "Ba Đình",
    "Hoàn Kiếm",
    "Hai Bà Trưng",
    "Đống Đa",
    "Tây Hồ",
    "Cầu Giấy",
    "Thanh Xuân",
    "Hoàng Mai",
    "Long Biên",
    "Nam Từ Liêm",
    "Bắc Từ Liêm",
    "Hà Đông",
  ],
};
export const wardOptions = {
  "Quận 1": [
    "Bến Nghé",
    "Bến Thành",
    "Cầu Kho",
    "Cầu Ông Lãnh",
    "Nguyễn Thái Bình",
    "Phạm Ngũ Lão",
    "Tân Định",
  ],
  "Ba Đình": [
    "Phúc Xá",
    "Trúc Bạch",
    "Vĩnh Phúc",
    "Cống Vị",
    "Liễu Giai",
    "Nguyễn Trung Trực",
    "Quán Thánh",
  ],
  "Quận 3": [
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 4",
    "Phường 5",
    "Phường 9",
    "Phường 10",
    "Phường 11",
    "Phường 12",
    "Phường 13",
    "Phường 14",
  ],
  "Quận 4": [
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 4",
    "Phường 5",
    "Phường 6",
    "Phường 8",
    "Phường 9",
    "Phường 10",
    "Phường 13",
    "Phường 14",
    "Phường 15",
    "Phường 16",
    "Phường 18",
  ],
  "Quận 5": [
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 4",
    "Phường 5",
    "Phường 6",
    "Phường 7",
    "Phường 8",
    "Phường 9",
    "Phường 10",
    "Phường 11",
    "Phường 12",
    "Phường 13",
    "Phường 14",
    "Phường 15",
  ],
  "Quận Bình Thạnh": [
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 5",
    "Phường 6",
    "Phường 7",
    "Phường 11",
    "Phường 12",
    "Phường 13",
    "Phường 14",
    "Phường 15",
    "Phường 17",
    "Phường 19",
    "Phường 21",
    "Phường 22",
    "Phường 24",
    "Phường 25",
    "Phường 26",
    "Phường 27",
    "Phường 28",
  ],
  "Quận Tân Bình": [
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 4",
    "Phường 5",
    "Phường 6",
    "Phường 7",
    "Phường 8",
    "Phường 9",
    "Phường 10",
    "Phường 11",
    "Phường 12",
    "Phường 13",
    "Phường 14",
    "Phường 15",
  ],
  "Hoàn Kiếm": [
    "Phường Đồng Xuân",
    "Phường Hàng Bạc",
    "Phường Hàng Bồ",
    "Phường Hàng Bông",
    "Phường Hàng Buồm",
    "Phường Hàng Đào",
    "Phường Hàng Gai",
    "Phường Hàng Mã",
    "Phường Hàng Trống",
    "Phường Lý Thái Tổ",
    "Phường Phan Chu Trinh",
    "Phường Trần Hưng Đạo",
    "Phường Tràng Tiền",
  ],
  "Hai Bà Trưng": [
    "Phường Bạch Đằng",
    "Phường Bách Khoa",
    "Phường Bạch Mai",
    "Phường Cầu Dền",
    "Phường Đống Mác",
    "Phường Đồng Nhân",
    "Phường Đồng Tâm",
    "Phường Lê Đại Hành",
    "Phường Minh Khai",
    "Phường Ngô Thì Nhậm",
    "Phường Nguyễn Du",
    "Phường Phạm Đình Hổ",
    "Phường Phố Huế",
    "Phường Quỳnh Lôi",
    "Phường Quỳnh Mai",
    "Phường Thanh Lương",
    "Phường Thanh Nhàn",
    "Phường Trương Định",
    "Phường Vĩnh Tuy",
  ],
  "Thành phố Thủ Đức": [
    "Phường An Khánh",
    "Phường An Lợi Đông",
    "Phường An Phú",
    "Phường Bình Chiểu",
    "Phường Bình Thọ",
    "Phường Bình Trưng Đông",
    "Phường Bình Trưng Tây",
    "Phường Cát Lái",
    "Phường Hiệp Bình Chánh",
    "Phường Hiệp Bình Phước",
    "Phường Hiệp Phú",
    "Phường Linh Chiểu",
    "Phường Linh Đông",
    "Phường Linh Tây",
    "Phường Linh Trung",
    "Phường Linh Xuân",
    "Phường Long Bình",
    "Phường Long Phước",
    "Phường Long Thạnh Mỹ",
    "Phường Long Trường",
    "Phường Phú Hữu",
    "Phường Phước Bình",
    "Phường Phước Long A",
    "Phường Phước Long B",
    "Phường Tam Bình",
    "Phường Tam Phú",
    "Phường Tăng Nhơn Phú A",
    "Phường Tăng Nhơn Phú B",
    "Phường Tân Phú",
    "Phường Thảo Điền",
    "Phường Thủ Thiêm",
    "Phường Trường Thạnh",
    "Phường Trường Thọ",
  ],
  "Quận 6": [
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 4",
    "Phường 5",
    "Phường 6",
    "Phường 7",
    "Phường 8",
    "Phường 9",
    "Phường 10",
    "Phường 11",
    "Phường 12",
    "Phường 13",
    "Phường 14",
  ],
  "Quận 7": [
    "Phường Tân Thuận Đông",
    "Phường Tân Thuận Tây",
    "Phường Tân Kiểng",
    "Phường Tân Hưng",
    "Phường Bình Thuận",
    "Phường Tân Quy",
    "Phường Phú Thuận",
    "Phường Tân Phú",
    "Phường Tân Phong",
    "Phường Phú Mỹ",
  ],
  "Quận 8": [
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 4",
    "Phường 5",
    "Phường 6",
    "Phường 7",
    "Phường 8",
    "Phường 9",
    "Phường 10",
    "Phường 11",
    "Phường 12",
    "Phường 13",
    "Phường 14",
    "Phường 15",
    "Phường 16",
  ],
  "Quận 10": [
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 4",
    "Phường 5",
    "Phường 6",
    "Phường 7",
    "Phường 8",
    "Phường 9",
    "Phường 10",
    "Phường 11",
    "Phường 12",
    "Phường 13",
    "Phường 14",
    "Phường 15",
  ],
  "Quận 11": [
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 4",
    "Phường 5",
    "Phường 6",
    "Phường 7",
    "Phường 8",
    "Phường 9",
    "Phường 10",
    "Phường 11",
    "Phường 12",
    "Phường 13",
    "Phường 14",
    "Phường 15",
    "Phường 16",
  ],
  "Quận 12": [
    "Phường An Phú Đông",
    "Phường Đông Hưng Thuận",
    "Phường Hiệp Thành",
    "Phường Tân Chánh Hiệp",
    "Phường Tân Hưng Thuận",
    "Phường Tân Thới Hiệp",
    "Phường Tân Thới Nhất",
    "Phường Thạnh Lộc",
    "Phường Thạnh Xuân",
    "Phường Thới An",
    "Phường Trung Mỹ Tây",
  ],
  "Quận Gò Vấp": [
    "Phường 1",
    "Phường 3",
    "Phường 4",
    "Phường 5",
    "Phường 6",
    "Phường 7",
    "Phường 8",
    "Phường 9",
    "Phường 10",
    "Phường 11",
    "Phường 12",
    "Phường 13",
    "Phường 14",
    "Phường 15",
    "Phường 16",
    "Phường 17",
  ],
  "Quận Phú Nhuận": [
    "Phường 1",
    "Phường 2",
    "Phường 3",
    "Phường 4",
    "Phường 5",
    "Phường 7",
    "Phường 8",
    "Phường 9",
    "Phường 10",
    "Phường 11",
    "Phường 13",
    "Phường 15",
    "Phường 17",
  ],
  "Quận Tân Phú": [
    "Phường Hiệp Tân",
    "Phường Hòa Thạnh",
    "Phường Phú Thạnh",
    "Phường Phú Thọ Hòa",
    "Phường Phú Trung",
    "Phường Sơn Kỳ",
    "Phường Tân Quý",
    "Phường Tân Sơn Nhì",
    "Phường Tân Thành",
    "Phường Tân Thới Hòa",
    "Phường Tây Thạnh",
  ],
  "Đống Đa": [
    "Phường Cát Linh",
    "Phường Hàng Bột",
    "Phường Khâm Thiên",
    "Phường Khương Thượng",
    "Phường Kim Liên",
    "Phường Láng Hạ",
    "Phường Láng Thượng",
    "Phường Nam Đồng",
    "Phường Ngã Tư Sở",
    "Phường Ô Chợ Dừa",
    "Phường Phương Liên",
    "Phường Phương Mai",
    "Phường Quang Trung",
    "Phường Quốc Tử Giám",
    "Phường Thịnh Quang",
    "Phường Thổ Quan",
    "Phường Trung Liệt",
    "Phường Trung Phụng",
    "Phường Trung Tự",
    "Phường Văn Chương",
    "Phường Văn Miếu",
  ],
  "Tây Hồ": [
    "Phường Bưởi",
    "Phường Nhật Tân",
    "Phường Phú Thượng",
    "Phường Quảng An",
    "Phường Thụy Khuê",
    "Phường Tứ Liên",
    "Phường Xuân La",
    "Phường Yên Phụ",
  ],
  "Cầu Giấy": [
    "Phường Dịch Vọng",
    "Phường Dịch Vọng Hậu",
    "Phường Mai Dịch",
    "Phường Nghĩa Đô",
    "Phường Nghĩa Tân",
    "Phường Quan Hoa",
    "Phường Trung Hòa",
    "Phường Yên Hòa",
  ],
  "Thanh Xuân": [
    "Phường Hạ Đình",
    "Phường Khương Đình",
    "Phường Khương Mai",
    "Phường Khương Trung",
    "Phường Kim Giang",
    "Phường Nhân Chính",
    "Phường Phương Liệt",
    "Phường Thanh Xuân Bắc",
    "Phường Thanh Xuân Nam",
    "Phường Thanh Xuân Trung",
    "Phường Thượng Đình",
  ],
  "Hoàng Mai": [
    "Phường Đại Kim",
    "Phường Định Công",
    "Phường Giáp Bát",
    "Phường Hoàng Liệt",
    "Phường Hoàng Văn Thụ",
    "Phường Lĩnh Nam",
    "Phường Mai Động",
    "Phường Tân Mai",
    "Phường Thanh Trì",
    "Phường Thịnh Liệt",
    "Phường Trần Phú",
    "Phường Tương Mai",
    "Phường Vĩnh Hưng",
    "Phường Yên Sở",
  ],
  "Long Biên": [
    "Phường Bồ Đề",
    "Phường Cự Khối",
    "Phường Đức Giang",
    "Phường Gia Thụy",
    "Phường Giang Biên",
    "Phường Long Biên",
    "Phường Ngọc Lâm",
    "Phường Ngọc Thụy",
    "Phường Phúc Đồng",
    "Phường Phúc Lợi",
    "Phường Sài Đồng",
    "Phường Thạch Bàn",
    "Phường Thượng Thanh",
    "Phường Việt Hưng",
  ],
  "Nam Từ Liêm": [
    "Phường Cầu Diễn",
    "Phường Đại Mỗ",
    "Phường Mễ Trì",
    "Phường Mỹ Đình 1",
    "Phường Mỹ Đình 2",
    "Phường Phú Đô",
    "Phường Phương Canh",
    "Phường Tây Mỗ",
    "Phường Trung Văn",
    "Phường Xuân Phương",
  ],
  "Bắc Từ Liêm": [
    "Phường Cổ Nhuế 1",
    "Phường Cổ Nhuế 2",
    "Phường Đông Ngạc",
    "Phường Đức Thắng",
    "Phường Liên Mạc",
    "Phường Minh Khai",
    "Phường Phú Diễn",
    "Phường Phúc Diễn",
    "Phường Tây Tựu",
    "Phường Thượng Cát",
    "Phường Thụy Phương",
    "Phường Xuân Đỉnh",
    "Phường Xuân Tảo",
  ],
  "Hà Đông": [
    "Phường Biên Giang",
    "Phường Đồng Mai",
    "Phường Dương Nội",
    "Phường Hà Cầu",
    "Phường Kiến Hưng",
    "Phường La Khê",
    "Phường Mộ Lao",
    "Phường Nguyễn Trãi",
    "Phường Phú La",
    "Phường Phú Lãm",
    "Phường Phú Lương",
    "Phường Phúc La",
    "Phường Quang Trung",
    "Phường Vạn Phúc",
    "Phường Văn Quán",
    "Phường Yên Nghĩa",
    "Phường Yết Kiêu",
  ],
};
